Repository FlakySL/translatable, pull requests merged in 2025-03, with the labels that each got.

#1 improve static translation retrieval
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/languages.rs
  src/lib.rs
  src/macros.rs
  src/translations.rs
  tests/static.rs
Labels: enhancement

#3 feat: translation object validation
  src/translations.rs
Labels: enhancement

#2 refactor/languages
  .gitignore
  flake.lock
  flake.nix
  src/languages.rs
  src/macros.rs
  src/translations.rs
Labels: enhancement

#4 refactor: improve code quality and add documentation
  README.md
  src/config.rs
  src/languages.rs
  src/lib.rs
  src/macros.rs
  src/translations.rs
Labels: documentation, enhancement

#5 Macro basic handling and working
  Cargo.lock
  Cargo.toml
  README.md
  flake.lock
  flake.nix
  rustfmt.toml
  src/macros.rs
  src/translations.rs
  tests/static.rs
  translatable/Cargo.toml
  translatable/src/lib.rs
  translatable/tests/test.rs
  translatable_proc/Cargo.toml
  translatable_proc/src/data/config.rs
  translatable_proc/src/data/mod.rs
  translatable_proc/src/data/translations.rs
  translatable_proc/src/languages.rs
  translatable_proc/src/lib.rs
  translatable_proc/src/macros.rs
  translatable_proc/src/translations/errors.rs
  translatable_proc/src/translations/generation.rs
  translatable_proc/src/translations/mod.rs
  translations/test.toml
Labels: documentation, enhancement

#10 Add templating
  README.md
  translatable/tests/test.rs
  translatable_proc/src/macros.rs
  translatable_proc/src/translations/generation.rs
Labels: can-be-merged, assigned, feature

#11 Repository metadata
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/SUPPORT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Cargo.toml
  GOVERNANCE.md
  LICENSE-APACHE
  LICENSE-MIT
  README-MACROS.md
  README.md
  SECURITY.md
  translatable/Cargo.toml
  translatable_proc/Cargo.toml
Labels: assigned, feature

#12 feat(config): add environment variable support for configuration overrides
  Cargo.lock
  GOVERNANCE.md
  SECURITY.md
  translatable_proc/Cargo.toml
  translatable_proc/src/data/config.rs
Labels: feature, unassigned
